site_name: Deutsch
theme:
  name: material
  features:
    - navigation.path
    - navigation.top
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
extra_css:
  - stylesheets/extra.css
nav:
  - Home: 'README.md'
  - 'Grammar':
    - 'Satzergänzungen': 'satzergaanzungen.md'
    - 'Modalverben': 'modalverben.md'
    - 'Reflexive Verbs': 'reflexive_verbs.md'
  - Words:
    - 'Januar': 'words_2401.md'
  - Phrases:
    - 'Januar': 'phrases_2401.md'
  - Sentenses:
    - 'Januar': 'sentenses_2401.md'